ventas/config/routes.rb
Ventas::Application.routes.draw do

  resources :detalles_movimientos_stocks_auxs do
    collection do
       get :autocomplete_producto_descripcion
    end
    collection do
      get :actualizar
    end
      collection do
      get :guardar_o_actualizar
    end
    collection do
      get :cantidad_producto
    end
  end

  resources :detalles_movimientos_stocks

  resources :movimientos_stocks

  resources :tipos_movimientos

  resources :detalles_facturas_ventas_auxs do
     collection do
       get :autocomplete_producto_descripcion
    end
    collection do
      get :actualizar
    end
      collection do
      get :guardar_o_actualizar
    end
    collection do
      get :precio_producto
    end
    
  end

  resources :helps
  
  match 'logout' => 'sesiones#destroy', as: :logout
  match 'conf_new' => 'configuracions#new'
  get 'login' => 'sesiones#new', as: :login
  get "signup" => "users#new", :as => "signup"
  
  resources :clientes 
  resources :reports do
    collection do
      get :consult_between
      get :change_data
    end
  end
  resources :funcionarios
  resources :users
  resources :roles
  resources :roles_usuarios
  resources :sesiones
  resources :localidads
  resources :factura_venta do
    collection do
       get :autocomplete_cliente_nombre
    end
     member do
       get :view
    end
    collection do
      get :eliminar_factura
    end

  end
  resources :departamentos
  resources :paginas_estaticas
  resources :configuracions
  resources :productos
  resources :detalle_factura_venta  

  resources :auditorias do
    member do
      post :index
    end
  end
 
  root to: 'sesiones#new'

end

ventas/app/models/cliente.rb
class Cliente < ActiveRecord::Base
  attr_accessible :num_identidad,:nombre, :apellido,:direccion,:telefono,:sexo, :id_localidad

  belongs_to :localidad, :foreign_key=>"id_localidad"

  validates :nombre,:apellido,:num_identidad,:direccion, :presence => true
  validates :num_identidad, :length => { :minimum => 6}, :uniqueness => true, :format => { :with => /\d\-|\d\./}
  validates :nombre, :length => { :minimum => 3}, :format => { :with => /\A[a-zA-Z\s]+\z/}
  validates :apellido, :length => { :minimum => 3}, :format => { :with => /\A[a-zA-Z\s]+\z/}
  validates :direccion, :length => { :minimum => 5}, :format => { :with => /\A[a-zA-Z\s\d\.\/]+\z/}
  validates :telefono, :length => { :minimum => 6},  :format => { :with => /^\d{3,4}\s\d{5,6}$/ }

  has_many :factura_venta
  def self.cliente_id()
  	 cliente=Cliente.find(:first)
  	 return cliente.id
  end
   def cliente_nombre
    "#{self.nombre}"
    end

end

ventas/app/controllers/clientes_controller.rb
#Requerido para obtener la Auditoria del ABM Producto:
require 'custom_logger'

class ClientesController < ApplicationController
  #
  # Antes de hacer cualquier cosa con este controler,
  # se verifica si hay permiso para el usuario logueado
  #
    before_filter :require_login

  # GET /clientes
  # GET /clientes.json

  def index
    @clientes = Cliente.paginate(:page => params[:page], :per_page => 10)
    @empresa= Configuracion.find(:first)
    @nombreempresa = @empresa.nombre_empresa
    @logo = @empresa.logo
    @direccion = @empresa.direccion
    @telefono = @empresa.telefono
    @funcionario = current_user.funcionario.full_name
    @fecha = Time.now.strftime("%d %b %Y, %H:%m")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clientes }
      format.pdf{render :layout => false}
    end
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @cliente = Cliente.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cliente }
  end
  end 

  # GET /clientes/new
  # GET /clientes/new.json
  def new
    @cliente = Cliente.new
    localidad_new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(params[:id])
    localidad_new
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(params[:cliente])
    localidad_new

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Los datos del Cliente se han creado correctamente.'}
        CustomLogger.info("Se ha creado un nuevo Cliente: Datos: Nombre: #{@cliente.nombre.inspect} , Apellido:#{@cliente.apellido.inspect}, Nro de CI o RUC: #{@cliente.num_identidad.inspect}, Direccion:#{@cliente.direccion.inspect}, Telefono:#{@cliente.telefono.inspect}, Sexo:#{@cliente.sexo.inspect} y Localidad:#{@cliente.localidad.nombre}. Usuario Responsable:#{current_user.funcionario.full_name.inspect}. Fecha y Hora: #{Time.now}")
        format.json { render json: @cliente, status: :created, location: @cliente }
        format.js   {render 'create'}
      else
        format.html { render action: "new" }
        CustomLogger.error("Error al intentar Crear un Nuevo Cliente. Usuario Responsable:#{current_user.funcionario.full_name.inspect}. Fecha y Hora: #{Time.now}")
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clientes/1
  # PUT /clientes/1.json
  def update
    @cliente = Cliente.find(params[:id])
    localidad_new

    nombre_antiguo= @cliente.nombre
    apellido_antiguo= @cliente.apellido
    num_doc_antiguo= @cliente.num_identidad
    direccion_antigua= @cliente.direccion
    telefono_antiguo= @cliente.telefono
    sexo_antiguo= @cliente.sexo
    localidad_antigua= @cliente.localidad.nombre

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        nombre_nuevo= @cliente.nombre
        apellido_nuevo= @cliente.apellido
        num_doc_nuevo= @cliente.num_identidad
        direccion_nueva= @cliente.direccion
        telefono_nuevo= @cliente.telefono
        sexo_nuevo= @cliente.sexo
        localidad_nueva= @cliente.localidad.nombre
        CustomLogger.info("Datos antes de realizar la Actualizacion de Cliente: Nombre: #{nombre_antiguo.inspect}, Apellido:#{apellido_antiguo.inspect}, Nro de RUC o CI: #{num_doc_antiguo.inspect}, Direccion: #{direccion_antigua.inspect}, Sexo:#{sexo_antiguo.inspect}, Localidad:#{localidad_antigua.inspect} .Usuario Responsable: #{current_user.funcionario.full_name.inspect}.Datos Actualizados: Nombre:#{nombre_nuevo.inspect}, Apellido:#{apellido_nuevo.inspect}, Nro de RUC o CI:#{num_doc_nuevo.inspect}, Direccion:#{direccion_nueva.inspect}, Telefono:#{telefono_nuevo.inspect}, Sexo:#{sexo_nuevo.inspect} y Localidad:#{localidad_nueva.inspect}. Fecha y Hora: #{Time.now}")
        format.html { redirect_to @cliente, notice: 'Los datos del Cliente se han actualizado correctamente.' }
        format.json { head :no_content }
      else
        CustomLogger.error("Error al intentar realizar actualizacion de los siguientes datos del Cliente: Nombre: #{nombre_antiguo.inspect}, Apellido:#{apellido_antiguo.inspect}, Nro de RUC o CI: #{num_doc_antiguo.inspect}, Direccion: #{direccion_antigua.inspect}, Sexo:#{sexo_antiguo.inspect}, Localidad:#{localidad_antigua.inspect} .Usuario Responsable: #{current_user.funcionario.full_name.inspect}. Fecha y Hora: #{Time.now}")
        format.html { render action: "edit" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente = Cliente.find(params[:id])
    @destruyo = false
    begin
      if @cliente.destroy
         @destruyo = true
      end
      notice= "Los datos del Cliente han sido eliminados"
      CustomLogger.info("Han sido eliminados los siguientes datos del Cliente: Nombre:#{@cliente.nombre.inspect}, Apellido:#{@cliente.apellido.inspect}, Nro de CI o RUC: #{@cliente.num_identidad.inspect}, Direccion:#{@cliente.direccion.inspect}, Telefono:#{@cliente.telefono.inspect}, Sexo:#{@cliente.sexo.inspect} y Localidad:#{@cliente.localidad.nombre}. Usuario Responsable: #{current_user.funcionario.full_name.inspect}. Fecha y Hora: #{Time.now}")
    rescue
      notice= "Los datos del Cliente no pueden ser eliminados"
      CustomLogger.error("No se pudo eliminar los siguientes datos del Cliente: Nombre: #{@cliente.nombre.inspect}, Apellido:#{@cliente.apellido.inspect}, Nro de CI o RUC: #{@cliente.num_identidad.inspect}, Direccion:#{@cliente.direccion.inspect}, Telefono:#{@cliente.telefono.inspect}, Sexo:#{@cliente.sexo.inspect} y Localidad:#{@cliente.localidad.nombre}. Usuario Responsable: #{current_user.funcionario.full_name.inspect}. Fecha y Hora: #{Time.now}")
    ensure
      respond_to do |format|
      format.js
    end
    end
  end

  def localidad_new
      @localidad= Localidad.new
      @departamentos=Departamento.all
  end

  def funcionario_create
      @localidad = Localidad.new(params[:funcionario])
       @departamentos=Departamento.all
      if @localidad.save
        flash[:notice] = "Los datos de la localidad se han creado correctamente."
      else
        flash[:notice] = "Se produjo inconvenientes al crear los datos de la Localidad"
      end
  end

end

ventas/app/helpers/clientes_helper.rb
module ClientesHelper
end

ventas/app/views/clientes/_form.html.erb
<div class="span8 offset2" style="margin-top:80px;">	
		<%= form_for @cliente,:validate => true do |f| %>
   		 <%= render 'mensajes/error_mensajes', object: f.object %>	
			<legend>Nuevo Cliente</legend>
			<div class="span8">
               
                   <div class="span3">
				        <%= f.label "Nombre (*)",class:"label"%>
					    <%= f.text_field :nombre,:id=>"txt_nombres",class: "span3", :placeholder => "Ingrese Nombre", :maxlength=>"25", :onkeypress => "return validarText(event, this)"%>
					    <%= f.label "RUC/Nro CI (*)",class:"label"%>
						<%= f.text_field :num_identidad ,class: "span3" ,:placeholder => "Ingrese Nº de RUC o CI",:maxlength=>"10" %>
						<%= f.label "Telefono ",class:"label"%>
					    <%= f.text_field :telefono ,class: "span3" , :placeholder => "xxx xxxxxx o xxxx xxxxx" ,:maxlength=>"15" %>
						<%= f.label "Localidad (*)",class:"label"%>
					    <div id="collectionlocalidad"> <%=render 'select_localidades'%></div>
			       			<i class="icon-plus-sign" title="editar"></i>&nbsp<a data-toggle="modal" href="#localidad" >Nueva Localidad</a>
                    </div>
					<div class="span3">
					     <%= f.label "Apellido  (*)",class:"label"%>
					 	 <%= f.text_field :apellido ,class: "span3" ,:placeholder => "Ingrese Apellido",:maxlength=>"25", :onkeypress => "return validarText(event, this)" %>
					 	 <%= f.label "Direccion  (*)",class:"label"%>
                         <%= f.text_field :direccion ,class: "span3" ,:placeholder => "Ingrese Direccion",:maxlength=>"35", :onkeypress => "return validarText(event, this)"  %>
					     <%= f.label "Sexo  (*)",class:"label"%><br/> 
						 <%= f.select(:sexo, ['M', 'F' ], id:"select", class: "span3")%>
					</div>
					
				</div>	
				<div class="span2 offset3" align="center"><br/>
						<%= f.submit "Guardar", class: "btn btn-primary"%>
						<%= link_to "Cancelar", clientes_path, class: "btn"%>
				</div>
	</div>	
<% end %>
	    			
	<div class="span2">
      <div id="localidad" class="modal hide fade in" style="display: none;">
        	 <%=render 'clientes/ventana_modal'%>
       </div>
    </div> 
     

ventas/app/views/clientes/_select_localidades.html.erb
<%=collection_select( "cliente", :id_localidad, Localidad.find(:all), :id , :nombre,  {}, {class: "span3" }) %>  

ventas/app/views/clientes/_ventana_modal.html.erb
<div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Nueva Localidad</h3>
</div>

<div class="modal-body">
         <p id="error" class="error"></p>
         <%= form_for@localidad, :remote => true do |f| %>
        <div class="span1">
            <%= f.label "Localidad (*)",class:"label"%>
            <%= f.text_field :nombre,class: "span3",:placeholder => "Ingrese Nueva Localidad",:maxlength=>"35", :onkeypress => "return validarText(event, this)" %> 
            <%= f.label "Departamento (*)",class:"label"%>
            <%=f.collection_select :id_departamento,Departamento.find(:all),:id,:nombre%>  
        </div>    
 </div> 

 <div class="modal-footer">
         <%= f.submit "Guardar", :class => 'btn btn-success'%>
         <a href="#" class="btn" data-dismiss="modal">Cancelar</a>
 </div> 

 <% end %>

ventas/app/views/clientes/create.js.erb
$("#cliente").hide();
$('.modal-backdrop').remove();
$("#collectiondepartamento").html("<%= escape_javascript(render 'localidads/select_departamentos') %>");

ventas/app/views/clientes/edit.html.erb
	<div class="container">
	  <div class="row">
	  	<% provide(:title, 'Editar Cliente') %>
        <%= render 'clientes/form'%>
      </div>
    </div>

ventas/app/views/clientes/index.html.erb
<label id="alert-destroy" class="alert alert-error span8 offset2" style="display: none; margin-top:10px;"></label>
<label id="alert-success" class="alert alert-success span8 offset2" style="display: none; margin-top:10px;"></label>
 <br/><br/><br/>
	  <div align="center">
		<h3> Lista de Clientes</h3>
		</div>
		
	   <div class="container-fluid">
	   	<div class="mismalinea">
	   		<label class="mismalinea">Filtrar:</label>
		    <input type="text" id="filtrar" placeholder="Filtrar" class="mismalinea-espacio">
	    </div>
			<table id="table" class="table table-bordered">
				<thead>
						<tr>
							<th>N°</th>
							<th>Nombre</th>
							<th>Apellido</th>
							<th>RUC/Nro CI</th>
							<th>Direccion</th>
							<th>Telefono</th>
							<th>Sexo</th>
							<th>Localidad</th>
							<th>Acciones</th>
						</tr>
				</thead>
				<tbody>
		            <% @clientes.each_with_index  do |cliente, i| %>
		            <% id = "page-" +i.to_s %> 					
						<tr>
							<td><%= i+1 %></td>
							<td><%= cliente.nombre %></td>
							<td><%= cliente.apellido %></td>
	                        <td><%= cliente.num_identidad %></td>
							<td><%= cliente.direccion %></td>
	                        <td><%= cliente.telefono%></td>
				            <td><%= cliente.sexo %></td>
				            <td><%= cliente.localidad.nombre %></td>
							<td><i class="icon-edit" title="editar"></i><%= link_to "Editar", edit_cliente_path(cliente) %> &nbsp &nbsp &nbsp   
							    		<i class="icon-remove-sign" title="borrar"></i><%= link_to "Borrar", cliente, :confirm => "Desea eliminar el cliente: "+cliente.nombre, :method => :delete, remote: true %>
							</td>
						</tr>
		            <% end %>
		            
				</tbody>
			</table>
	    		<%=will_paginate %>	
	  </div>
	   <div align="center">
			<i class="icon-plus-sign" title="editar"></i>&nbsp<%= link_to 'Nuevo Cliente', new_cliente_path %>&nbsp&nbsp
			<h8> | </h8>&nbsp&nbsp
			<i class="icon-file" title="editar"></i>&nbsp<%= link_to 'Ver en PDF', clientes_path(:format => 'pdf'), :target => '_blank'%>
	  </div>		

	  <!-- SCRIPT ALERTA DE BORRADO -->
<script type="text/javascript">
	function cerrar(){
		$("#alert-destroy").hide();

	}
</script>

ventas/app/views/clientes/new.html.erb
<div class="container">
	  <div class="row">
		<% provide(:title, 'Nuevo Cliente') %>
		<%= render 'clientes/form'%>
	  </div>
</div>

ventas/app/views/clientes/show.html.erb
<br/>
<% provide(:title, @cliente.nombre) %>
<div align="center">
	<h3>Datos del Cliente </h3><br/>
</div>
<div class="container-fluid">
    <table class="table table-bordered">
		<thead>
			<tr>
				<th>Nombre</th>
				<th>Apellido</th>
				<th>RUC/Nro CI</th>
				<th>Direccion</th>
				<th>Telefono</th>
				<th>Sexo</th>
				<th>Localidad</th>
				<th>Acciones</th>
			</tr>
		</thead>
	  <tbody>
	  	<tr>
			<td><%= @cliente.nombre %></td>
			<td><%= @cliente.apellido%></td>
			<td><%= @cliente.num_identidad%></td>
			<td><%= @cliente.direccion%></td>
			<td><%= @cliente.telefono %></td>
			<td><%= @cliente.sexo %></td>
			<td><%= @cliente.localidad.nombre %></td>
            <td><i class="icon-edit" title="editar"></i><%= link_to "Editar", edit_cliente_path(@cliente) %> &nbsp &nbsp &nbsp   
		
			</td>
		</tr>
	   </tbody>
  </table>
  </div>
  <div align="center">
     	<i class="icon-plus-sign" title="editar"></i>&nbsp<%= link_to 'Nuevo Cliente', new_cliente_path %>&nbsp&nbsp
     	<h8> | </h8>&nbsp&nbsp
     	<i class="icon-list-alt"></i>&nbsp<%= link_to 'Ir a la Lista', clientes_path %>
   </div>

   