ventas/config/routes.rb
Ventas::Application.routes.draw do

  resources :detalles_movimientos_stocks_auxs do
    collection do
       get :autocomplete_producto_descripcion
    end
    collection do
      get :actualizar
    end
      collection do
      get :guardar_o_actualizar
    end
    collection do
      get :cantidad_producto
    end
  end

  resources :detalles_movimientos_stocks

  resources :movimientos_stocks

  resources :tipos_movimientos

  resources :detalles_facturas_ventas_auxs do
     collection do
       get :autocomplete_producto_descripcion
    end
    collection do
      get :actualizar
    end
      collection do
      get :guardar_o_actualizar
    end
    collection do
      get :precio_producto
    end
    
  end

  resources :helps
  
  match 'logout' => 'sesiones#destroy', as: :logout
  match 'conf_new' => 'configuracions#new'
  get 'login' => 'sesiones#new', as: :login
  get "signup" => "users#new", :as => "signup"
  
  resources :clientes 
  resources :reports do
    collection do
      get :consult_between
      get :change_data
    end
  end
  resources :funcionarios
  resources :users
  resources :roles
  resources :roles_usuarios
  resources :sesiones
  resources :localidads
  resources :factura_venta do
    collection do
       get :autocomplete_cliente_nombre
    end
     member do
       get :view
    end
    collection do
      get :eliminar_factura
    end

  end
  resources :departamentos
  resources :paginas_estaticas
  resources :configuracions
  resources :productos
  resources :detalle_factura_venta  

  resources :auditorias do
    member do
      post :index
    end
  end
 
  root to: 'sesiones#new'

end

ventas/app/models/localidad.rb
class Localidad < ActiveRecord::Base
 
  attr_accessible :nombre,:id_departamento
  
  has_many :funcionarios
  has_many :clientes
  belongs_to :departamento, :foreign_key=>"id_departamento"
  
  validates :nombre, presence: true,:length => { :minimum => 3}, :format => { :with => /\A[a-zA-Z\s\.]+\z/ }, :uniqueness =>{:message => "Esta Localidad ya esta registrada en el sistema"}

end

ventas/app/controllers/localidads_controller.rb
require 'custom_logger'

class LocalidadsController < ApplicationController
  #
  # Antes de hacer cualquier cosa con este controler,
  # se verifica si hay permiso para el usuario logueado
  #
    before_filter :require_login

  # GET /localidads
  # GET /localidads.json
  def index
    @localidads = Localidad.paginate(:page => params[:page], :per_page => 10)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @localidads }
    end
  end

  # GET /localidads/1
  # GET /localidads/1.json
  def show
    @localidad = Localidad.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @localidad }
    end
  end

  # GET /localidads/new
  # GET /localidads/new.json
  def new
    @localidad = Localidad.new
    departamento_new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @localidad }
    end
  end

  # GET /localidads/1/edit
  def edit
    @localidad = Localidad.find(params[:id])
     departamento_new
  end

  # POST /localidads
  # POST /localidads.json
  def create
    @localidad = Localidad.new(params[:localidad])
     departamento_new
     
    respond_to do |format|
      if @localidad.save
        format.html { redirect_to @localidad, notice: 'Los datos de la Localidad se han creado correctamente' }
        CustomLogger.info("Se ha creado una nueva Localidad:#{@localidad.nombre.inspect} perteneciente al departamento de: #{@localidad.departamento.nombre.inspect} .Usuario Responsable:#{current_user.funcionario.full_name.inspect}. Fecha y Hora: #{Time.now}")
        format.json { render json: @localidad, status: :created, location: @localidad }
        format.js{}
      else
        format.html { render action: "new" }
        CustomLogger.error("Error al intentar Crear una Nueva Localidad. Usuario Responsable:#{current_user.funcionario.full_name.inspect}. Fecha y Hora: #{Time.now}")
        format.json { render json: @localidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /localidads/1
  # PUT /localidads/1.json
  def update
    @localidad = Localidad.find(params[:id])
    departamento_new
    localidad_antigua= @localidad.nombre
    departamento_antiguo= @localidad.departamento.nombre
    respond_to do |format|
      if @localidad.update_attributes(params[:localidad])
        localidad_nueva= @localidad.nombre
        departamento_nuevo= @localidad.departamento.nombre
        CustomLogger.info("Datos antes de realizar la Actualizacion: Localidad: #{localidad_antigua.inspect} y Departamento: #{departamento_antiguo.inspect} .Usuario Responsable: #{current_user.funcionario.full_name.inspect} ; Nuevos Datos: Localidad: #{localidad_nueva.inspect} y Departamento: #{departamento_nuevo.inspect}. Fecha y Hora: #{Time.now}")
        format.html { redirect_to @localidad, notice: 'Los datos de la Localidad se han actualizado correctamente' }
        format.json { head :no_content }
      else
        CustomLogger.error("Error al intentar realizar la Actualizacion de los siguientes datos de Localidad: Localidad: #{localidad_antigua.inspect} y Departamento: #{departamento_antiguo.inspect}. Usuario Responsable: #{current_user.funcionario.full_name.inspect}. Fecha y Hora: #{Time.now}")
        format.html { render action: "edit" }
        format.json { render json: @localidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /localidads/1
  # DELETE /localidads/1.json
  def destroy
    @localidad = Localidad.find(params[:id])
    @destruyo = false
    begin
    if @localidad.destroy
      @destruyo = true
    end
    notice= "Los datos de la Localidad han sido eliminados"
    CustomLogger.info("La Localidad: #{@localidad.nombre.inspect} y el Departamento:#{@localidad.departamento.nombre.inspect} han sido eliminados. Usuario Responsable: #{current_user.funcionario.full_name.inspect} , Fecha y Hora: #{Time.now}")
    rescue
    notice= "Los datos de la Localidad no pueden ser eliminados"

    CustomLogger.error(" Error al intentar eliminar la Localidad: #{@localidad.nombre.inspect} y el Departamento:#{@localidad.departamento.nombre.inspect} ha sido eliminados. Usuario Responsable: #{current_user.funcionario.full_name.inspect}. Fecha y Hora: #{Time.now}")
    ensure
      respond_to do |format|
      format.js
    end
  end
  end
  def departamento_new
      @departamento= Departamento.new
     
  end
end

ventas/app/helpers/localidads_helper.rb
module LocalidadsHelper
end

ventas/app/views/localidads/_form.html.erb
<div class="span8 offset2" style="margin-top:80px;">
    <%= form_for @localidad, :validate => true do |f| %>
          <%= render 'mensajes/error_mensajes', object: f.object %>
             <legend>Nueva Localidad</legend>
             <div class="span8">

                  <div class="span2">
						          <%= f.label "Localidad (*)",class:"label"%>
						          <%= f.text_field :nombre,class: "span3",:placeholder => "Ingrese Localidad",:maxlength=>"35", :onkeypress => "return validarText(event, this)" %>	
	                    <%= f.label "Departamento (*)",class:"label"%>
	                	   <div id="collectiondepartamento"> <%=render 'select_departamentos'%></div>
					            <i class="icon-plus-sign"></i>&nbsp<a data-toggle="modal" href="#departamento" > Nuevo Departamento</a>
                  </div> 

               </div>
        
        <div class="span2 offset3" align="center"><br/>
						<%= f.submit "Guardar", class: "btn btn-primary"%>
						<%= link_to "Cancelar", localidads_path, class: "btn"%>
				</div>
	</div>	
<% end %>
	    			
	<div class="span2">
      <div id="departamento" class="modal hide fade in" style="display: none;">
        	 <%=render 'localidads/ventana_modal'%>
       <div>
    </div> 
     
   



     
    

ventas/app/views/localidads/_select_departamentos.html.erb
<%=collection_select("localidad", :id_departamento, Departamento.find(:all), :id, :nombre, {},  {class: "span3" })%> 

ventas/app/views/localidads/_ventana_modal.html.erb
<div class="modal-header">
  <a class="close" data-dismiss="modal">×</a>
     <h3>Nuevo Departamento</h3>
</div>

<div class="modal-body">
    <p id="notice"><%= notice %></p>
        <%= form_for@departamento, remote:true do |f| %>
            <div class="span3">
  						<%= f.label "Departamento:",class:"label"%>
  						<%= f.text_field :nombre,class: "span3" ,:placeholder => "Ingrese Nuevo Departamento",:maxlength=>"35", :onkeypress => "return validarText(event, this)" %>
				    </div> 

</div>

<div class="modal-footer">
            <%= f.submit "Guardar", :class => 'btn btn-success'%>
            <a href="#" class="btn" data-dismiss="modal">Cerrar</a>
            
</div>
            

<% end %>

ventas/app/views/localidads/create.js.erb
$("#localidad").hide();
$("#collectionlocalidad").html("<%= escape_javascript(render 'clientes/select_localidades') %>");
$('.modal-backdrop').remove();

ventas/app/views/localidads/edit.html.erb
<div class="container">
    <div class="row">
		<% provide(:title, 'Editar Localidad') %>
		<%= render 'localidads/form'%>
	</div>
</div>		

ventas/app/views/localidads/index.html.erb
  <label id="alert-destroy" class="alert alert-error span8 offset2" style="display: none; margin-top:10px;"></label>
<label id="alert-success" class="alert alert-success span8 offset2" style="display: none; margin-top:10px;"></label>
  <br/>
  <%= form_tag localidads_path, :method => 'get' do %>
  <div class="span8 offset2">
  <div align="center">
	<h3> Lista de Localidades</h3>
	</div>
   
   	   <div class="mismalinea">
	   		<label class="mismalinea">Filtrar:</label>
		   <input type="text" id="filtrar" placeholder="Filtrar" class="mismalinea-espacio">
	    </div>
		<table id="table" class="table table-bordered">
			<thead>
					<tr>
						<th>Nombre</th>
						<th>Departamento</th>
						<th>Acciones</th>
					</tr>
			</thead>
			<tbody>
	            <% @localidads.each  do |localidad| %>					
					<tr>
						<td><%= localidad.nombre %></td>
			            <td><%= localidad.departamento.nombre %></td>
						<td><i class="icon-edit" title="editar"></i><%= link_to "Editar", edit_localidad_path(localidad) %> &nbsp &nbsp &nbsp   
						    		<i class="icon-remove-sign" title="borrar"></i><%= link_to "Borrar",localidad, :confirm => "Desea eliminar la siguiente localidad:"+localidad.nombre, :method => :delete, remote: true %>
						</td>
					</tr>
	            <% end %>
			</tbody>
		</table>
		<%=will_paginate %>
		<div align="center">
		<i class="icon-plus-sign"></i>&nbsp<%= link_to 'Nueva Localidad', new_localidad_path %>
  </div>
  </div>
   		
  <% end %>
<script type="text/javascript">
	function cerrar(){
		$("#alert-destroy").hide();

	}
</script>

ventas/app/views/localidads/new.html.erb
<div class="container">
    <div class="row">
		<% provide(:title, 'Nueva Localidad') %>
		<%= render 'localidads/form'%>
	</div>
</div>		

ventas/app/views/localidads/show.html.erb
<br/>
<% provide(:title, @localidad.nombre) %>
<div class="span8 offset2">
	<div align="center">
		<h3>Datos de la Localidad </h3><br/>
	</div>

    <table class="table table-bordered">
		<thead>
			<tr>
				<th>Nombre</th>
				<th>Departamento</th>
				<th>Acciones</th>
			</tr>
		</thead>
	  <tbody>
	  	<tr>
			<td><%= @localidad.nombre %></td>
			<td><%= @localidad.departamento.nombre %></td>
            <td><i class="icon-edit" title="editar"></i><%= link_to "Editar", edit_localidad_path(@localidad) %> &nbsp &nbsp &nbsp   
			    
			</td>
		</tr>
	   </tbody>
  </table>
  <div align="center">
     <i class="icon-plus-sign"></i>&nbsp<%= link_to 'Nueva Localidad', new_localidad_path %>&nbsp&nbsp
     <h8> | </h8>&nbsp&nbsp
     <i class="icon-list-alt"></i>&nbsp<%= link_to 'Ir a la Lista', localidads_path %>
   </div>
  </div>
  

   