ventas/config/routes.rb
Ventas::Application.routes.draw do

  resources :detalles_movimientos_stocks_auxs do
    collection do
       get :autocomplete_producto_descripcion
    end
    collection do
      get :actualizar
    end
      collection do
      get :guardar_o_actualizar
    end
    collection do
      get :cantidad_producto
    end
  end

  resources :detalles_movimientos_stocks

  resources :movimientos_stocks

  resources :tipos_movimientos

  resources :detalles_facturas_ventas_auxs do
     collection do
       get :autocomplete_producto_descripcion
    end
    collection do
      get :actualizar
    end
      collection do
      get :guardar_o_actualizar
    end
    collection do
      get :precio_producto
    end
    
  end

  resources :helps
  
  match 'logout' => 'sesiones#destroy', as: :logout
  match 'conf_new' => 'configuracions#new'
  get 'login' => 'sesiones#new', as: :login
  get "signup" => "users#new", :as => "signup"
  
  resources :clientes 
  resources :reports do
    collection do
      get :consult_between
      get :change_data
    end
  end
  resources :funcionarios
  resources :users
  resources :roles
  resources :roles_usuarios
  resources :sesiones
  resources :localidads
  resources :factura_venta do
    collection do
       get :autocomplete_cliente_nombre
    end
     member do
       get :view
    end
    collection do
      get :eliminar_factura
    end

  end
  resources :departamentos
  resources :paginas_estaticas
  resources :configuracions
  resources :productos
  resources :detalle_factura_venta  

  resources :auditorias do
    member do
      post :index
    end
  end
 
  root to: 'sesiones#new'

end

ventas/app/controllers/factura_venta_controller.rb
#Requerido para obtener la Auditoria del ABM Producto:
require 'custom_logger'

class FacturaVentaController < ApplicationController
    before_filter :require_login
    autocomplete :cliente, :nombre,:extra_data => [:id,:nombre],:display_value => :cliente_nombre
  # GET /factura_venta
  # GET /factura_venta.json
  def index

    @facturas_ventas = FacturaVentum.paginate(:page => params[:page], :per_page => 10)
  

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @factura_venta }
      format.pdf{render :layout => false}
    end
  end

  # GET /factura_venta/1
  # GET /factura_venta/1.json
  def show
    @factura_ventum = FacturaVentum.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @factura_ventum }
      format.pdf{render :layout => false}
    end
  end

  # GET /factura_venta/new
  # GET /factura_venta/new.json
  def new
    @factura_ventum = FacturaVentum.new
    cliente_new
    destroy_detalle_factura_venta_aux
    detalle_factura_venta_aux
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @factura_ventum }
    end
  end

  # GET /factura_venta/1/edit
  def edit
    @factura_ventum = FacturaVentum.find(params[:id])
    detalle_factura_venta_aux
  end

  # POST /factura_venta
  # POST /factura_venta.json
  def create
     @factura_ventum = FacturaVentum.new(params[:factura_ventum])
     cliente_new
    respond_to do |format|
      if @factura_ventum.save
        CustomLogger.info("Se ha creado una nueva factura: Datos: Nro Factura: #{ @factura_ventum.nro_factura.inspect} ,Fecha:#{ @factura_ventum.fecha.inspect},Cliente: #{ @factura_ventum.cliente.nombre.inspect},Condicion de Pago:#{ @factura_ventum.condicion_de_pago.nombre_condicion_de_pago.inspect},Tipo de Valor:#{ @factura_ventum.tipo_valor_pago.descripcion.inspect}, Total IVA 5:#{@factura_ventum.total_iva5.inspect},Total IVA 10:#{ @factura_ventum.total_iva10.inspect},Descuento:#{ @factura_ventum.total_descuento.inspect},Total IVA :#{ @factura_ventum.total_iva.inspect},Monto Total:#{ @factura_ventum.monto_total.inspect}. Usuario Responsable:#{current_user.funcionario.full_name.inspect}. Fecha y Hora: #{Time.now}")
        @factura_venta=FacturaVentum.find(:last)
        @detalles_facturas_ventas_auxs=DetalleFacturaVentaAux.find(:all)
        @detalles_facturas_ventas_auxs.each  do |detalle_factura_venta_aux|
           @detalle_factura_venta= DetalleFacturaVentum.new(:id_factura_venta=>@factura_venta.id,:id_producto=>detalle_factura_venta_aux.id_producto,:cantidad=>detalle_factura_venta_aux.cantidad,:descuento=>detalle_factura_venta_aux.descuento)
           @detalle_factura_venta.save
           @stock=Stock.find(:first ,:conditions=>['id_producto = ? ',detalle_factura_venta_aux.id_producto])
           @stock=Stock.find(@stock.id)
           @stock.update_attributes(:cantidad=>@stock.cantidad-detalle_factura_venta_aux.cantidad)
        end
        @libro_caja=LibroCaja.find(:first)
        @detalle_libro_caja=DetalleLibroCaja.new(:id_libro_caja=>@libro_caja.id,:id_funcionario=>@factura_venta.id_funcionario,:id_tipo_documento=>1,:fecha=>Date.today,:descripcion=>"Ventas de Mercaderias",:ingreso=>@factura_ventum.monto_total,:egreso=>0,:nro_documento=>@factura_ventum.nro_factura)
        @detalle_libro_caja.save
        @libro_caja.update_attributes(:saldo_final=>@libro_caja.saldo_final+@factura_ventum.monto_total)
        destroy_detalle_factura_venta_aux
        format.html { redirect_to @factura_ventum, notice: 'Los datos de las Factura se han creado correctamente.'}
        format.json { render json: @factura_ventum, status: :created, location: @factura_ventum}
        format.js   {render 'create'}
      else
        format.html { render action: "new" }
        #CustomLogger.error("Error al intentar Crear un Nuevo Cliente. Usuario Responsable:#{current_user.funcionario.full_name.inspect}. Fecha y Hora: #{Time.now}")
        format.json { render json: @factura_ventum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /factura_venta/1
  # PUT /factura_venta/1.json
  def update
    @factura=FacturaVentum.find(:last)
    @factura_ventum = FacturaVentum.find(@factura.id)
    respond_to do |format|
      if @factura_ventum.update_attributes(params[:factura_ventum])
        @factura_ventum.update_attributes(:total_descuento=>params[:total_descuento],:total_iva5=>params[:total_iva5],:total_iva10=>params[:total_iva10],:total_iva=>params[:total_iva],:monto_total=>params[:monto_total])
        CustomLogger.info("Se ha creado una Nueva Factura de Ventas con los siguientes datos: Numero de Factura: #{@factura_ventum.nro_factura.inspect} , Cliente:#{@factura_ventum.cliente.nombre.inspect}, Funcionario: #{current_user.funcionario.full_name.inspect}, Fecha: #{@factura_ventum.fecha.inspect}, Condicion de Pago: #{@factura_ventum.condicion_de_pago.nombre_condicion_de_pago.inspect}, Tipo de Valor: #{@factura_ventum.tipo_valor_pago.descripcion.inspect}, Total IVA 5: #{@factura_ventum.total_iva5.inspect}, Total IVA 10: #{@factura_ventum.total_iva10.inspect}, Total IVA: #{@factura_ventum.total_iva.inspect}, Descuento: #{@factura_ventum.total_descuento.inspect} y Monto Total: #{@factura_ventum.monto_total}. Usuario Responsable:#{current_user.funcionario.full_name.inspect}. Fecha y Hora: #{Time.now}")
        @libro_caja=LibroCaja.find(:first)
        @tipo_documento=TipoDocumento.find(:first)
        @detalle_libro_caja=DetalleLibroCaja.new(:id_libro_caja=>@libro_caja.id,:id_funcionario=>@factura_ventum.id_funcionario,:id_tipo_documento=>@tipo_documento.id,:nro_asiento=>1,:fecha=>Date.today,:descripcion=>"Ventas de Mercaderias",:ingreso=>1,:egreso=>0,:nro_documento=>@factura_ventum.nro_factura)
        @detalle_libro_caja.save
        format.html { redirect_to @factura_ventum, notice: 'Factura ventum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        CustomLogger.error("Error al intentar Crear una Nueva Factura. Usuario Responsable:#{current_user.funcionario.full_name.inspect}. Fecha y Hora: #{Time.now}")
        format.json { render json: @factura_ventum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /factura_venta/1
  # DELETE /factura_venta/1.json
  def destroy
     @factura_ventum = FacturaVentum.find(params[:id])
     @factura_ventum.monto_total
     @detalles_factura_ventas = DetalleFacturaVentum.find(:all,:conditions=>['id_factura_venta = ? ',@factura_ventum.id])
     @detalles_factura_ventas.each  do |detalle_factura_venta|
     detalle_factura_venta.destroy
     end     
     @factura_ventum.destroy
     CustomLogger.info("Se ha anulado  Factura de Ventas con los siguientes datos: Nro de Factura: #{@factura_ventum.nro_factura.inspect} , Cliente:#{@factura_ventum.cliente.nombre.inspect}, y Monto Total: #{@factura_ventum.monto_total}. Usuario Responsable:#{current_user.funcionario.full_name.inspect}. Fecha y Hora: #{Time.now}")
       
    respond_to do |format|
       format.html { redirect_to factura_venta_url }
      format.json { render json: @factura_ventum }
    end
  end
 
  def detalle_factura_venta_aux
      @detalle_factura_venta_aux  = DetalleFacturaVentaAux.new
      @detalles_factura_ventas = DetalleFacturaVentaAux.listas_productos
  end
  def cliente_new
      @cliente= Cliente.new
     
  end
  def eliminar_factura
    
  end
  def view
      @empresa= Configuracion.find(:first)
    @nombreempresa = @empresa.nombre_empresa
    @logo = @empresa.logo
    @ruc = @empresa.ruc
    @timbrado = @empresa.timbrado
    @vencimiento = @empresa.timbrado_vencimiento
    @direccion = @empresa.direccion
    @telefono = @empresa.telefono
    @factura_venta= FacturaVentum.find(params[:id])
    @cliente=@factura_venta.cliente
    @detalles_factura_venta=DetalleFacturaVentum.find(:all,:conditions=>['id_factura_venta = ? ',@factura_venta.id])
 end
  def destroy_detalle_factura_venta_aux
     @detalles_facturas_ventas_auxs=DetalleFacturaVentaAux.find(:all)
     @detalles_facturas_ventas_auxs.each  do |detalle_factura_venta_aux|
        detalle_factura_venta_aux.destroy
      end
  end
end

ventas/app/helpers/factura_venta_helper.rb
module FacturaVentaHelper
end

ventas/app/views/factura_venta/_form.html.erb
<div class="mover">

    <%= form_for(@factura_ventum,:validate => true) do |f| %>
       <%= render 'mensajes/error_mensajes', object: f.object %>
          <legend class="span10">Nueva Factura </legend><br/>
           <div class="container">
              <div class= "span11" id="cabecera">
                  <div class="span2" style="margin-top:10px;">
                     <%= f.label :Nro_de_Factura,class:"label"%>
                     <%= f.text_field :nro_factura,:readonly => true,:value=>FacturaVentum.actual_nro_factura()%><br/>
                     <%= f.label :fecha,class:"label"%><br/>
                     <%= f.text_field :fecha,:value => Date.today,:readonly => true%>
                  </div>
                  <div class="span3 offset1" style="margin-top:10px; margin-right:20px;">
                       <%= f.label "Clientes:",class:"label"%>
                       <%= f.autocomplete_field :id_cliente,autocomplete_cliente_nombre_factura_venta_path,:id_element=>"#cliente_id",:onblur=>"validarCampoVacioCliente(this)",:maxlength=>"25"%>  
                        <%= f.hidden_field :id_cliente,id:"cliente_id"%>
                       <a data-toggle="modal" href="#cliente" > <i class="icon-plus-sign"></i></a>
                        <div id="cliente_error" style="display: none; " >
                               <label>El campo no puede estar vacio </label>
                        </div>
                        <div id="solo_letras_error" class="span3" style="display: none; " >
                               <label>El texto no es valido</label>
                        </div>
                        <%= f.label "Condicion de Pago:",class:"label"%>
                        <%=f.collection_select :id_condicion_pago,CondicionDePago.find(:all),:id,:nombre_condicion_de_pago,id:"select",:selected => 1%>
                  </div>  
                  <div class="span3 " style="margin-top:10px;">
                     <%= f.label "Funcionario:",class:"label"%>
                     <%= f.label current_user.funcionario.nombres+" " + current_user.funcionario.apellidos %> 
                     <%= f.hidden_field :id_funcionario,:value =>current_user.funcionario.id,:readonly => true %> 
                      <%= f.label "Tipo de Valor:",class:"label"%>
                      <%= f.collection_select :id_tipo_valor,TipoValorPago.find(:all),:id,:descripcion,:selected => 1 %>
                  </div> 
                </div>  
              <div class="span10">
                <div class="span2" style="margin-left:10px; margin-top:5px; margin-bottom:5px;">  
                       <a style='cursor: pointer;' onclick="muestra_oculta('producto')"><i class="icon-plus-sign"></i>Cargar Producto</a>
                </div>  
                <div id="producto" style="display: none;">
                      <%=render 'factura_venta/producto'%>
                </div>
              </div>
              <div class="span10" style="margin-left:10px; width:1120px;">
                    <div id="lista_productos">
                      <%=render 'factura_venta/lista_productos'%>
                    </div>   
              </div> 
              <div class = "span11"> 
                  <div align="center">
                    
                    <div class="span11" id="totales" style="margin-left:0px;">
                      <%= render 'factura_venta/totales_ivas'%>
                    </div>        
                  </div>                
                  <div class="span2 offset8"><br/>
                      <%= f.submit "Guardar", class: "btn btn-primary", :id=>"botonguardar"%>
                      <%= link_to "Cancelar", factura_venta_path, class: "btn"%>
                  </div> 
              </div>    
         </div>
        <% end %>
      </div>  
         <div id="cliente" class="modal hide fade in" style="display:none;">
           <%=render 'factura_venta/ventana_modal'%>
         </div>
          

ventas/app/views/factura_venta/_lista_productos.html.erb
<script type="text/javascript">
    $(document).ready(function() {
        $("table").tablecloth({
          theme: "stats",
          striped: true,
          sortable: true,
          condensed: true
        });

       var buscarEnTabla = function() {
        var table = $('#table');
        var value = this.value;
        table.find('tr').each(function(index, row) {
            var allCells = $(row).find('td');
            if(allCells.length > 0) {
                var found = false;
                allCells.each(function(index, td) {
                    var regExp = new RegExp(value, 'i');
                    if(regExp.test($(td).text())) {
                        found = true;
                        return false;
                    }
                });
                if (found == true) $(row).show();
                else $(row).hide();
            }
        });
    };
     
 });
    
  </script>
  <%= form_tag detalles_facturas_ventas_auxs_path,:method => 'get' do %>
    
     <div class="container-fluid">
    <table class="table table-bordered" >
    <thead>
      <tr>
        <th>Producto</th>
        <th>Cantidad</th>
        <th>Precio</th>
        <th>Descuento</th>
        <th>Total</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% if @detalles_factura_ventas==nil
      else
        @detalles_factura_ventas.each  do |detalle_factura_venta_aux| %>  
          <tr>
          <td><%=detalle_factura_venta_aux.producto.descripcion %></td>
          <td><%=detalle_factura_venta_aux.cantidad%></td>
          <td><%=detalle_factura_venta_aux.producto.precio_unitario %></td>
          <td><%=(detalle_factura_venta_aux.producto.precio_unitario*detalle_factura_venta_aux.cantidad*detalle_factura_venta_aux.descuento)/100 %></td>
          <td><%=detalle_factura_venta_aux.cantidad*detalle_factura_venta_aux.producto.precio_unitario-((detalle_factura_venta_aux.producto.precio_unitario*detalle_factura_venta_aux.cantidad*detalle_factura_venta_aux.descuento)/100) %></td>
                <td><i class="icon-edit" title="editar"></i><%=link_to "editar",edit_detalle_factura_venta_aux_path(detalle_factura_venta_aux),:onclick=>"muestra_oculta('producto')",:remote=>true%> &nbsp &nbsp &nbsp   
              <i class="icon-remove-sign" title="borrar"></i><%= link_to "borrar",detalle_factura_venta_aux, :confirm => "Desea Eliminar el producto "+ detalle_factura_venta_aux.producto.descripcion, :remote => true,:method => :delete %>
          </td>
        </tr>
      <% end %>
    <% end %>

     </tbody>
  </table>
</div>
<% end %>

ventas/app/views/factura_venta/_producto.html.erb
<script type="text/javascript">
    $(document).ready(function () {
        $('#guardar_o_actualizar').on("click", function() {
            var _id= $("#id").val();
             var _id_producto =$("#id_producto").val();
             var _cantidad = $("#cantidad").val();
             var _descuento = $("#descuento").val();
             $.ajax({
                    url: $(this).attr('ajax_path'),
                    data: {"id":_id ,"id_producto":_id_producto,"cantidad":_cantidad,"descuento":_descuento},
                    async: true,
                    dataType: 'script'
                    });
                    return false;
         });
        $('#cantidad').on("click", function() {
             var _id_producto = $("#id_producto").val();
             $.ajax({
                    url: $(this).attr('ajax_path'),
                    data: {"id_producto":_id_producto},
                    async: true,
                    dataType: 'script'
                    });
                    return false;
         });

    });
</script>
       <div class="span11" id="productmodal">
                    <div class="span4">     
                     <%= hidden_field_tag :id,params[:id],:value=>@id%>
                        <label class="label">Producto:</label>
                         <%= autocomplete_field_tag :id_producto,params[:id_producto] ,autocomplete_producto_descripcion_detalles_facturas_ventas_auxs_path,:id_element=>"#id_producto",:value=>@producto,:id=>"descripcion",:onblur=>"validarCampoVacioProducto(this)",:maxlength=>"25"%>
                         <%= hidden_field_tag :id_producto,params[:id_producto],:id=>"id_producto",:value=>@producto_id%>
                         <div id="producto_error" class="span3" style="display: none; " >
                               <label>El campo no puede estar vacio </label>
                        </div>
                        <div id="solo_letras_error" class="span3" style="display: none; " >
                               <label>El texto no es valido</label>
                        </div>
        
                    </div>
                    <div id="precio_producto" class="span1" style="display: none; ">
                              <%=render 'detalles_facturas_ventas_auxs/precio_producto'%>
                    </div>   
                    <div class="span2 ">
                       <label class="label">Cantidad:</label>
                       <%= text_field_tag :cantidad,params[:cantidad] ,class:"span1",:id=>"cantidad",:ajax_path => precio_producto_detalles_facturas_ventas_auxs_path,:onblur=>"validarCampoCantidad(this)",:maxlength=>"3",:value=>@cantidad%>
                        <div id="cantidad_error" class="span3" style="display:none; ">
                               <label>El campo no puede estar vacio </label>
                        </div>
                        <div id="numero_error" class="span3" style="display:none; ">
                               <label>El campo debe de ser numerico </label>
                        </div>
                        <div id="stock_cantidad_error" class="span3" style="display:none; ">
                               <label>La cantidad introducida supera a la cantidad del stock </label>
                        </div>
                  </div>
                    <div class="span2" >
                        <label class="label">Descuento:</label>
                        <%= text_field_tag :descuento,params[:descuento], class:"span1", :id=>"descuento",:onblur=>"validarCampoDescuento(this)",:maxlength=>"3",:value=>@descuento%>
                        <div id="descuento_error" class="span3" style="display:none; ">
                               <label>El campo no puede estar vacio </label>
                        </div>
                        <div id="numero_descuento_error" class="span3" style="display:none; ">
                               <label>El campo debe de ser numerico </label>
                        </div>
                        <div id="rango_descuento_error" class="span3" style="display:none; ">
                               <label>Debe ingresar en un rango de 0 a 100 porciento </label>
                        </div>
                    </div> 
                                
                    <div class="span2 offset4" align="center" style="margin-top:25px;">
                       <%= link_to "Guardar", "#", :id => "guardar_o_actualizar",  :class => 'btn btn-success',:ajax_path => guardar_o_actualizar_detalles_facturas_ventas_auxs_path%>
                       <button type="button" class="btn" onclick="cancelar()">Cancelar</button>
                    </div>  
                </div>  <br/><br/>

                             

ventas/app/views/factura_venta/_totales_ivas.html.erb
 <div class="span2 offset6 iva" style="font-size: 12px;" align="right">
    <strong>Descuento (Gs): </strong>
  </div>
  <div class="span2">
      <%= text_field("factura_ventum",:total_descuento,:value => FacturaVentum.descuento(),:readonly => true)%>  
  </div>
 <div class="span10" style="font-size: 12px;">
    <div class="span2 iva" style="margin-left:-20px;">
      <strong>Total IVA 5%:</strong>
    </div>
    <div class="span2" style="margin-left:-30px;">
      <%= text_field("factura_ventum",:total_iva5,:value => FacturaVentum.factura_total_iva5(),:readonly => true )%>
    </div>
    <div class="span2 iva">
      <strong>Total IVA 10%:</strong>
    </div>
    <div class="span2" style="margin-left:-30px;">
      <%= text_field("factura_ventum",:total_iva10,:value => FacturaVentum.factura_total_iva10(),:readonly => true) %>
    </div>
    <div class="span2 iva" >
      <strong>Total IVA:</strong>
    </div>
    <div class="span2" style="margin-left:-30px;">
     <%= text_field("factura_ventum",:total_iva,:value => FacturaVentum.factura_total_iva(),:readonly => true )%> 
   </div>
  </div>
  <div class="span2 offset6 iva" style="font-size: 12px; " align="right">
    <strong>TOTAL (Gs):</strong>
  </div>
  <div class="span2" style="margin-left:30px;">
     <%= text_field("factura_ventum",:monto_total,:value => FacturaVentum.factura_monto_total(),:readonly => true) %> 
  </div>

ventas/app/views/factura_venta/_ventana_modal.html.erb
<div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
        <h3>Nuevo Cliente</h3>
</div>

<div class="modal-body">
  <p id="error" class="error"></p>
       <%= form_for@cliente, remote:true do |f| %>
     		 <legend>Nuevo Cliente</legend>
            <div class="span8">
               <div class="span3">
                  <%= f.label "Nombre (*)",class:"label"%>
                  <%= f.text_field :nombre,:id=>"txt_nombres",class: "span3", :placeholder => "Ingrese Nombre", :maxlength=>"25"%>
                  <%= f.label "RUC/Nro CI (*)",class:"label"%>
                  <%= f.text_field :num_identidad ,class: "span3" ,:placeholder => "Ingrese Nº de RUC o CI",:maxlength=>"10" %>
                  <%= f.label "Telefono ",class:"label"%>
                  <%= f.text_field :telefono ,class: "span3" , :placeholder => "xxx xxxxxx o xxxx xxxxx" ,:maxlength=>"15" %>
                  <%= f.label "Localidad (*)",class:"label"%>
                  <div id="collectionlocalidad"> <%= render 'clientes/select_localidades'%></div>
                </div>
              <div class="span3">
                 <%= f.label "Apellido  (*)",class:"label"%>
                 <%= f.text_field :apellido ,class: "span3" ,:placeholder => "Ingrese Apellido",:maxlength=>"25" %>
                 <%= f.label "Direccion  (*)",class:"label"%>
                  <%= f.text_field :direccion ,class: "span3" ,:placeholder => "Ingrese Direccion",:maxlength=>"35"  %>
                 <%= f.label "Sexo  (*)",class:"label"%><br/> 
               <%= f.select(:sexo, ['M', 'F' ], id:"select", class: "span3")%>
             </div>
          
        </div>    
 </div>	

  	     <div class="modal-footer">
              <%= f.submit "Guardar", :class => 'btn btn-success'%>
              <a href="#" class="btn" data-dismiss="modal">Salir</a>
         </div>
      <% end %>

ventas/app/views/factura_venta/edit.html.erb
<div class="mover"><br/>
	<div class="container">
	  <div class="row">
			<% provide(:title, 'Actualizar Factura') %>
			<%= render 'factura_venta/form'%>
	 </div>
	</div>	
</div>

ventas/app/views/factura_venta/index.html.erb
 <br/>
    <div align="center">
    <h3> Lista de Facturas</h3>
    </div>
    
     <div class="container-fluid">
      <div class="mismalinea">
        <label class="mismalinea">Filtrar:</label>
       <input type="text" id="filtrar" placeholder="Filtrar" class="mismalinea-espacio">
      </div>
      <table id="table" class="table table-bordered">
        <thead>
            <tr>
              <th>Cliente</th>
              <th>Fecha</th>
              <th>Nro Factura</th>
              <th>Iva 5%</th>
              <th>Iva 10%</th>
              <th>Descuento</th>
              <th>Total</th>
              <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            <% @facturas_ventas.each  do |f| %>
              <% if f.monto_total==0.0 %>
                 <% else %>         
                  <tr>
                    <td><%= f.cliente.nombre %></td>
                    <td><%= f.fecha%></td>
                    <td><%= f.nro_factura %></td>
                    <td><%= f.total_iva5 %></td>
                    <td><%= f.total_iva10 %></td>
                    <td><%= f.total_descuento %></td>
                    <td><%= f.monto_total %></td>
                    <td><i class="icon-remove-sign" title="anular">&nbsp</i><%= link_to "Anular",f, :confirm => "Desea eliminar la factura nro: "+f.nro_factura.to_s, :method => :delete%> &nbsp &nbsp &nbsp   
                        <i class="icon-file" title="ver"></i></i>&nbsp<%= link_to "Ver",view_factura_ventum_path(f,:format => 'pdf'), :target => '_blank' %>
                    </td>
                  </tr>
                <% end %>
            <% end %>
                
        </tbody>
      </table>
          <%=will_paginate @facturas_ventas%> 
    </div>
     <div align="center">
      <i class="icon-plus-sign"></i>&nbsp<%= link_to 'Cargar Nueva Factura', new_factura_ventum_path %>
    </div>    

ventas/app/views/factura_venta/new.html.erb
<div class="container">
	  <div class="row">
			<% provide(:title, 'Nueva Factura') %>
			<%= render 'factura_venta/form'%>
	 </div>
	</div>	

ventas/app/views/factura_venta/show.html.erb
<br/>
    <div align="center">
    <h3> Factura Agregada</h3>
    </div>
    
     <div class="container-fluid">
      <table id="table" class="table table-bordered">
        <thead>
            <tr>
              <th>Cliente</th>
              <th>Fecha</th>
              <th>Nro Factura</th>
              <th>Iva 5%</th>
              <th>Iva 10%</th>
              <th>Descuento</th>
              <th>Total</th>
              <th>Acciones</th>
            </tr>
        </thead>
        <tbody>        
            <tr>
              <td><%= @factura_ventum.cliente.nombre %></td>
              <td><%= @factura_ventum.fecha%></td>
              <td><%= @factura_ventum.nro_factura %></td>
              <td><%= @factura_ventum.total_iva5 %></td>
              <td><%= @factura_ventum.total_iva10 %></td>
              <td><%= @factura_ventum.total_descuento %></td>
              <td><%= @factura_ventum.monto_total %></td>
              <td><i class="icon-remove-sign" title="anular"></i><%= link_to "anular",@factura_ventum, :confirm => "Desea anular la factura nro "+ @factura_ventum.nro_factura.to_s,:method => :delete %> &nbsp &nbsp &nbsp   
                  <i class="icon-file" title="ver"></i></i>&nbsp <%= link_to "ver",view_factura_ventum_path(@factura_ventum,:format => 'pdf'), :target => '_blank'%>
              </td>
            </tr>         
        </tbody>
      </table>
    </div>
     <div align="center">
      <i class="icon-plus-sign"></i><%= link_to 'Nueva Factura', new_factura_ventum_path %>&nbsp&nbsp
    <h8> | </h8>&nbsp&nbsp
    <i class="icon-list-alt"></i>&nbsp<%= link_to 'Ir a la Lista', factura_venta_path %>


    </div> 