ventas/config/routes.rb
Ventas::Application.routes.draw do

  resources :detalles_movimientos_stocks_auxs do
    collection do
       get :autocomplete_producto_descripcion
    end
    collection do
      get :actualizar
    end
      collection do
      get :guardar_o_actualizar
    end
    collection do
      get :cantidad_producto
    end
  end

  resources :detalles_movimientos_stocks

  resources :movimientos_stocks

  resources :tipos_movimientos

  resources :detalles_facturas_ventas_auxs do
     collection do
       get :autocomplete_producto_descripcion
    end
    collection do
      get :actualizar
    end
      collection do
      get :guardar_o_actualizar
    end
    collection do
      get :precio_producto
    end
    
  end

  resources :helps
  
  match 'logout' => 'sesiones#destroy', as: :logout
  match 'conf_new' => 'configuracions#new'
  get 'login' => 'sesiones#new', as: :login
  get "signup" => "users#new", :as => "signup"
  
  resources :clientes 
  resources :reports do
    collection do
      get :consult_between
      get :change_data
    end
  end
  resources :funcionarios
  resources :users
  resources :roles
  resources :roles_usuarios
  resources :sesiones
  resources :localidads
  resources :factura_venta do
    collection do
       get :autocomplete_cliente_nombre
    end
     member do
       get :view
    end
    collection do
      get :eliminar_factura
    end

  end
  resources :departamentos
  resources :paginas_estaticas
  resources :configuracions
  resources :productos
  resources :detalle_factura_venta  

  resources :auditorias do
    member do
      post :index
    end
  end
 
  root to: 'sesiones#new'

end

ventas/app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
  
  attr_accessible :num_identidad,:nombres, :apellidos,:direccion,:telefono,:estado_civil,:sexo,:id_localidad,:id_estado_funcionario,:id_funcion
 
  belongs_to :localidad, :foreign_key=>"id_localidad"
  belongs_to :estados_funcionario, :foreign_key=>"id_estado_funcionario"
  belongs_to :funcion, :foreign_key=>"id_funcion"
  has_many :users
  has_many :factura_venta
  
  validates :num_identidad,presence: true, :length => { :minimum => 6}, :uniqueness => {:message => "El funcionario con este Nro de Documento ya se encuentra registrado"}, :format => { :with => /\d\-|\d\./}
  validates :nombres, presence: true,:length => { :minimum => 3}, :format => { :with => /\A[a-zA-Z\s]+\z/ }
  validates :apellidos,presence: true, :length => { :minimum => 3}, :format => { :with => /\A[a-zA-Z\s]+\z/ }
  validates :direccion,presence: true,  :length => { :minimum =>3}, :format => { :with => /\A[a-zA-Z\s\d\.\/]+\z/}
  validates :telefono, :length => { :minimum => 6}, :format => { :with => /^\d{3,4}\s\d{5,6}$/ }

  def full_name
   self.nombres.capitalize + ' ' + self.apellidos.capitalize
  end
  def self.funcionario_id()
     funcionario=Funcionario.find(:first)
     return funcionario.id
  end
end

ventas/app/controllers/funcionarios_controller.rb
#Requerido para obtener la Auditoria del ABM Producto:
require 'custom_logger'

class FuncionariosController < ApplicationController
    before_filter :require_login
  # GET /funcionarios
  # GET /funcionarios.json
  def index
     @funcionarios = Funcionario.paginate(:page => params[:page], :per_page => 10)
      respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @funcionarios }
    end
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
    @funcionario = Funcionario.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @funcionario }
    end
  end

  # GET /funcionarios/new
  # GET /funcionarios/new.json
  def new
    @funcionario = Funcionario.new
    localidad_new
    @estados_funcionarios=EstadosFuncionario.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @funcionario }
    end
  end

  # GET /funcionarios/1/edit
  def edit
    @funcionario = Funcionario.find(params[:id])
     localidad_new
  end


 # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(params[:funcionario])
     localidad_new
    respond_to do |format|
      if @funcionario.save
        format.html {  redirect_to @funcionario, notice: 'Los datos del funcionario se han creado correctamente' }
        CustomLogger.info("Se ha creado un Nuevo Funcionario con los siguientes datos: Nombre:#{@funcionario.nombres.inspect}, Apellido:#{@funcionario.apellidos.inspect}, Nro de RUC o CI:#{@funcionario._num_identidad.inspect}, Direccion:#{@funcionario.direccion.inspect}, Telefono:#{@funcionario.telefono.inspect}, Estado Civil:#{@funcionario.estado_civil.inspect}, Sexo:#{@funcionario.sexo.inspect}, Localidad:#{@funcionario.localidad.nombre.inspect}, Estado del Funcionario:#{@funcionario.estados_funcionario.descripcion.inspect}, Funcion:#{@funcionario.funcion.nombre.inspect}. Usuario Responsable:#{current_user.funcionario.full_name.inspect}. Fecha y Hora: #{Time.now}")
        format.json { render json: @funcionario, status: :created, location: @funcionario }
        format.js   {}
      else
        format.html { render action: "new" }
        CustomLogger.error("Error al intentar Crear un Nuevo Funcionario. Usuario Responsable:#{current_user.funcionario.full_name.inspect}. Fecha y Hora: #{Time.now}")
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end


  # PUT /funcionarios/1
  # PUT /funcionarios/1.json
  def update
    @funcionario = Funcionario.find(params[:id])
    localidad_new

    nombre_antiguo= @funcionario.nombres
    apellido_antiguo= @funcionario.apellidos
    num_identidad_antiguo= @funcionario.num_identidad
    direccion_antigua= @funcionario.direccion
    telefono_antiguo= @funcionario.telefono
    estado_civil_antiguo= @funcionario.estado_civil
    sexo_antiguo= @funcionario.sexo
    localidad_antigua= @funcionario.localidad.nombre
    estado_funcionario_antiguo= @funcionario.estados_funcionario.descripcion
    funcion_antiguo= @funcionario.funcion.nombre 
    
    respond_to do |format|
      if @funcionario.update_attributes(params[:funcionario])
            nombre_nuevo= @funcionario.nombres
            apellido_nuevo= @funcionario.apellidos
            num_identidad_nuevo= @funcionario.num_identidad
            direccion_nueva= @funcionario.direccion
            telefono_nuevo= @funcionario.telefono
            estado_civil_nuevo= @funcionario.estado_civil
            sexo_nuevo= @funcionario.sexo
            localidad_nueva= @funcionario.localidad.nombre
            estado_funcionario_nuevo= @funcionario.estados_funcionario.descripcion
            funcion_nuevo= @funcionario.funcion.nombre 

            CustomLogger.info("Datos antes de realizar la Actualizacion de Funcionarios: Nombre: #{nombre_antiguo.inspect}, Apellido:#{apellido_antiguo.inspect}, Num de CI o RUC:#{num_identidad_antiguo.inspect}, Direccion:#{direccion_antigua.inspect}, Telefono:#{telefono_antiguo.inspect}, Estado Civil:#{estado_civil_antiguo.inspect}, Sexo:#{sexo_antiguo.inspect}, Localidad:#{localidad_antigua.inspect}, Estado del Funcionario:#{estado_funcionario_antiguo.inspect}, Funcion:#{funcion_antiguo.inspect} .Usuario Responsable:#{current_user.funcionario.full_name.inspect}. Datos Actualizados: Nombre:#{nombre_nuevo.inspect}, Apellido:#{apellido_nuevo.inspect}, Num de CI o RUC:#{num_identidad_nuevo.inspect}, Direccion:#{direccion_nueva.inspect}, Telefono:#{telefono_nuevo.inspect}, Estado Civil:#{estado_civil_nuevo.inspect}, Sexo:#{sexo_nuevo.inspect}, Localidad:#{localidad_nueva.inspect}, Estado del Funcionario:#{estado_funcionario_nuevo.inspect}, Funcion:#{funcion_nuevo.inspect} . Fecha y Hora: #{Time.now}")
            format.html { redirect_to @funcionario, notice: 'Funcionario was successfully updated.' }
            format.json { head :no_content }
       else
        CustomLogger.error("Error al intentar realizar la Actualizacion de los siguientes datos del Funcionario: Nombre: #{nombre_antiguo.inspect}, Apellido:#{apellido_antiguo.inspect}, Num de CI o RUC:#{num_identidad_antiguo.inspect}, Direccion:#{direccion_antigua.inspect}, Telefono:#{telefono_antiguo.inspect}, Estado Civil:#{estado_civil_antiguo.inspect}, Sexo:#{sexo_antiguo.inspect}, Localidad:#{localidad_antigua.inspect}, Estado del Funcionario:#{estado_funcionario_antiguo.inspect}, Funcion:#{funcion_antiguo.inspect} .Usuario Responsable:#{current_user.funcionario.full_name.inspect}. Fecha y Hora: #{Time.now}")
        format.html { render action: "edit" }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario = Funcionario.find(params[:id])
    @destruyo = false
    begin
    if @funcionario.destroy
      @destruyo = true
    end
    notice= "Los datos de Funcionario han sido eliminados"
    CustomLogger.info("Han sido eliminados los siguientes datos del Funcionario:Nombre:#{@funcionario.nombres.inspect}, Apellido:#{@funcionario.apellidos.inspect}, Nro de RUC o CI:#{@funcionario._num_identidad.inspect}, Direccion:#{@funcionario.direccion.inspect}, Telefono:#{@funcionario.telefono.inspect}, Estado Civil:#{@funcionario.estado_civil.inspect}, Sexo:#{@funcionario.sexo.inspect}, Localidad:#{@funcionario.localidad.nombre.inspect}, Estado del Funcionario:#{@funcionario.estados_funcionario.descripcion.inspect}, Funcion:#{@funcionario.funcion.nombre.inspect}. Usuario Responsable: #{current_user.funcionario.full_name.inspect}. Fecha y Hora: #{Time.now}")
    rescue
    notice= "No pueden eliminarse lo datos de Funcionario"
    CustomLogger.error("Error al intentar eliminar los siguientes datos del Funcionario:Nombre:#{@funcionario.nombres.inspect}, Apellido:#{@funcionario.apellidos.inspect}, Nro de RUC o CI:#{@funcionario._num_identidad.inspect}, Direccion:#{@funcionario.direccion.inspect}, Telefono:#{@funcionario.telefono.inspect}, Estado Civil:#{@funcionario.estado_civil.inspect}, Sexo:#{@funcionario.sexo.inspect}, Localidad:#{@funcionario.localidad.nombre.inspect}, Estado del Funcionario:#{@funcionario.estados_funcionario.descripcion.inspect}, Funcion:#{@funcionario.funcion.nombre.inspect}. Usuario Responsable: #{current_user.funcionario.full_name.inspect}. Fecha y Hora: #{Time.now}")
    ensure
      respond_to do |format|
      format.js
    end
  end
  end
  def localidad_new
      @localidad= Localidad.new
  end
end

ventas/app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

ventas/app/views/funcionarios/_form.html.erb
<div class="span8 offset2" style="margin-top:80px;">	
	<%= form_for @funcionario, :validate => true do |f| %>
   		 <%= render 'mensajes/error_mensajes', object: f.object %>	
			<legend>Nuevo Funcionario</legend>
			<div class="span8">
               
                   <div class="span3">
						<%= f.label "Nombre (*)",class:"label"%>
						<%= f.text_field :nombres,class: "span3",:placeholder => "Ingrese Nombre",:maxlength=>"25", :onkeypress => "return validarText(event, this)" %><br/>
						<%= f.label "Nro de RUC o CI (*)",class:"label"%>
						<%= f.text_field :num_identidad,class: "span3",:placeholder => "Ingrese Nº de RUC o CI",:maxlength=>"10" %><br/>
						<%= f.label "Telefono",class:"label"%>
					    <%= f.text_field :telefono,class: "span3",:placeholder => "xxx xxxxxx o xxxx xxxxx",:maxlength=>"15" %><br/>
						<%= f.label "Estado Funcionario (*)",class:"label"%>
			            <%=f.collection_select(:id_estado_funcionario, EstadosFuncionario.find(:all), :id, :descripcion, {}, {class: "span3"})%>   
			             <%= f.label "Localidad (*)",class:"label"%>
					     <div id="collectionlocalidad"> <%=render 'select_localidades'%></div>   
			       		 <i class="icon-plus-sign"></i>&nbsp<a data-toggle="modal" href="#localidad" >Nueva Localidad</a> 	<br/>   
		            </div>
		            <div class="span2">
		             	<%= f.label "Apellido (*)",class:"label"%>
						<%= f.text_field :apellidos,class: "span3",:placeholder => "Ingrese Apellido",:maxlength=>"25", :onkeypress => "return validarText(event, this)"  %><br/>
						<%= f.label "Direccion (*)",class:"label"%>
						<%= f.text_field :direccion,class: "span3",:placeholder => "Ingrese Direccion",:maxlength=>"35", :onkeypress => "return validarText(event, this)"  %><br/>
  						<%= f.label "Funcion (*)",class:"label"%>
					    <%=f.collection_select(:id_funcion, Funcion.find(:all), :id, :nombre, {}, {class: "span3"} )%>
						<%= f.label "Estado Civil (*)",class:"label"%>
						<%= f.select(:estado_civil, ['Casado', 'Soltero', 'Viudo', 'Separado' ])%>
						<%= f.label "Sexo (*)",class:"label"%>
						<%= f.select(:sexo, ['M', 'F' ],id:"select")%>
					</div>
					
				</div>	
				<div class="span2 offset2" align="center"><br/>
						<%= f.submit "Guardar", class: "btn btn-primary"%>
						<%= link_to "Cancelar", funcionarios_path, class: "btn"%>
				</div>
	</div>	
<% end %>
	    			
	<div class="span2">
      <div id="localidad" class="modal hide fade in" style="display: none;">
        	 <%=render 'funcionarios/ventana_modal'%>
       <div>
    </div> 

     
     

ventas/app/views/funcionarios/_select_localidades.html.erb
<%=collection_select( "funcionario", :id_localidad, Localidad.find(:all), :id , :nombre,  {}, {class: "span3" }) %>  

ventas/app/views/funcionarios/_ventana_modal.html.erb
<div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
        <h3>Nueva Localidad</h3>
</div>

<div class="modal-body">
         <p id="notice"><%= notice %></p>
         <%= form_for@localidad, remote:true do |f| %>
        <div class="span1">
            <%= f.label "Localidad:",class:"label"%>
            <%= f.text_field :nombre,class: "span3",:placeholder => "Ingrese Nueva Localidad",:maxlength=>"35", :onkeypress => "return validarText(event, this)" %> 
            <%= f.label "Departamento:",class:"label"%>
            <%=f.collection_select :id_departamento,Departamento.find(:all),:id,:nombre%>  
        </div>    
 </div> 

 <div class="modal-footer">
         <%= f.submit "Guardar", :class => 'btn btn-success'%>
         <a href="#" class="btn" data-dismiss="modal">Cancelar</a>
 </div> 

 <% end %>

ventas/app/views/funcionarios/create.js.erb
$("#funcionario").hide();
$('.modal-backdrop').remove();
$("#collectionfuncionario").html("<%= escape_javascript(render 'users/select_funcionarios') %>");

ventas/app/views/funcionarios/edit.html.erb
<div class="container">
	  <div class="row">
			<% provide(:title, 'Editar Funcionario') %>
			<%= render 'funcionarios/form'%>
	 </div>
</div>

ventas/app/views/funcionarios/index.html.erb
  <label id="alert-destroy" class="alert alert-error span8 offset2" style="display: none; margin-top:10px;"></label>
 <label id="alert-success" class="alert alert-success span8 offset2" style="display: none; margin-top:10px;"></label>
  <br/><br/><br/>
  <div align="center">
	<h3> Lista de Funcionarios</h3>
	</div>
   <div class="container-fluid">
    	<div class="mismalinea">
	   		<label class="mismalinea">Filtrar:</label>
		   <input type="text" id="filtrar" placeholder="Filtrar" class="mismalinea-espacio">
	    </div>
		<table id="table" class="table table-bordered">
			<thead>
					<tr>
						<th>Nombres</th>
						<th>Apellidos</th>
						<th>Nro de RUC o CI</th>
						<th>Direccion</th>
						<th>Telefono</th>
						<th>Estado Civil</th>
						<th>Sexo</th>
						<th>Localidad</th>
						<th>Estado Funcionario</th>
						<th>Funcion</th>
						<th>Acciones</th>
					</tr>
			</thead>
			<tbody>
	            <% @funcionarios.each  do |funcionario| %>					
					<tr>
						<td><%= funcionario.nombres %></td>
						<td><%= funcionario.apellidos %></td>
                        <td><%= funcionario.num_identidad %></td>
						<td><%= funcionario.direccion %></td>
                        <td><%= funcionario.telefono%></td>
                        <td><%= funcionario.estado_civil %></td>
			            <td><%= funcionario.sexo %></td>
			             <td><%= funcionario.localidad.nombre %></td>
			             <td><%= funcionario.estados_funcionario.descripcion %></td>
			             <td><%= funcionario.funcion.nombre %></td>
						<td><i class="icon-edit" title="editar"></i><%= link_to "Editar", edit_funcionario_path(funcionario) %> &nbsp &nbsp &nbsp   
						    		<i class="icon-remove-sign" title="borrar"></i><%= link_to "Borrar", funcionario, :confirm => "Desea eliminar el funcionario "+funcionario.nombres, :method => :delete, remote: true %>
						</td>
					</tr>
	            <% end %>
			</tbody>
		</table>
		<%=will_paginate %>
  </div>
	<div align="center">
		<i class="icon-plus-sign"></i>&nbsp<%= link_to 'Nuevo Funcionario', new_funcionario_path %>
	</div>
<!-- SCRIPT ALERTA DE BORRADO -->
<script type="text/javascript">
	function cerrar(){
		$("#alert-destroy").hide();

	}
</script>

ventas/app/views/funcionarios/new.html.erb
<div class="container">
	  <div class="row">
			<% provide(:title, 'Nuevo Funcionario') %>
			<%= render 'funcionarios/form'%>
	 </div>
</div>	

ventas/app/views/funcionarios/show.html.erb
<br/>
<% provide(:title, @funcionario.nombres) %>
<div align="center">
	<h3>Datos del Funcionario </h3><br/>
</div>
<div class="container-fluid">
    <table class="table table-bordered">
		<thead>
			<tr>
				<th>Nombres</th>
				<th>Apellidos</th>
				<th>Nro de RUC o CI</th>
				<th>Direccion</th>
				<th>Telefono</th>
				<th>Estado Civil</th>
				<th>Sexo</th>
				<th>Localidad</th>
				<th>Estado Funcionario</th>
				<th>Funcion</th>
				<th>Acciones</th>
			</tr>
		</thead>
	  <tbody>
	  	<tr>
			<td><%= @funcionario.nombres %></td>
			<td><%= @funcionario.apellidos%></td>
			<td><%= @funcionario._num_identidad%></td>
			<td><%= @funcionario.direccion%></td>
			<td><%= @funcionario.telefono %></td>
			<td><%= @funcionario.estado_civil %></td>
			<td><%= @funcionario.sexo %></td>
			<td><%= @funcionario.localidad.nombre %></td>
			<td><%= @funcionario.estados_funcionario.descripcion %></td>
			<td><%= @funcionario.funcion.nombre %></td>
            <td><i class="icon-edit" title="editar"></i><%= link_to "Editar", edit_funcionario_path(@funcionario) %> &nbsp &nbsp &nbsp   
			   
			</td>
		</tr>
	   </tbody>
  </table>
  </div>
  <div align="center">
   	<i class="icon-plus-sign"></i>&nbsp<%= link_to 'Nuevo Funcionario', new_funcionario_path %>&nbsp&nbsp
   	<h8> | </h8>&nbsp&nbsp
    <i class="icon-list-alt"></i>&nbsp<%= link_to 'Ir a la Lista', funcionarios_path %>
  </div>

   